#!/bin/sh
#
# Generates a random mac address and configures en0
###################################################

MAC=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
sudo airport -z
sudo ifconfig en0 ether $MAC
networksetup -detectnewhardware
